export const DEFAULT_TIMEOUT = 10 * 60 * 1000;
export const DEFAULT_NOTIFICATION_TIMEOUT = DEFAULT_TIMEOUT;
export const DEFAULT_FIRE_NOTIFICATION_TIMEOUT = 20 * 1000;
export const DEFAULT_CONDITION_DELAY = 500;
